# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('punti_interesse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstensioneInteresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=128, unique=True, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name': 'Estensione Interesse',
                'verbose_name_plural': 'Estensione Interessi',
            },
        ),
        migrations.CreateModel(
            name='InteresseSpecifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=128, unique=True, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name': 'Interesse Specifico',
                'verbose_name_plural': 'Interessi Specifici',
            },
        ),
        migrations.CreateModel(
            name='QualitaInteresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=128, unique=True, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name': 'Qualità Interesse',
                'verbose_name_plural': 'Qualità Interessi',
            },
        ),
        migrations.AlterField(
            model_name='tipointeresse',
            name='descrizione',
            field=models.CharField(max_length=128, unique=True, verbose_name='Descrizione'),
        ),
        migrations.AddField(
            model_name='interessespecifico',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punti_interesse.TipoInteresse'),
        ),
    ]
