# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-10 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('punti_interesse', '0002_auto_20190110_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoInteresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Coordinate')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome')),
                ('localita', models.CharField(max_length=128, verbose_name='Località')),
                ('valle', models.CharField(max_length=128, verbose_name='Valle')),
                ('valenza', models.CharField(max_length=128, verbose_name='Titolo della valenza')),
                ('visitabile', models.BooleanField(verbose_name='Visitabile')),
                ('visitabile2', models.BooleanField(verbose_name='Visitabile per persone con ridotta capacità motoria o sensoriale')),
                ('periodo', models.CharField(max_length=256, verbose_name='Periodo di visita consigliato')),
                ('istituto', models.CharField(max_length=128, verbose_name='Istituto di tutela')),
                ('descr_breve', models.TextField(max_length=256, verbose_name='Descrizione oggetto breve')),
                ('descr_estesa', models.TextField(max_length=1024, verbose_name='Descrizione oggetto estesa')),
                ('descr_sito', models.TextField(max_length=256, verbose_name='Descrizione oggetto breve')),
                ('motivo', models.TextField(max_length=256, verbose_name='Motivo per la fruizione')),
                ('data', models.DateField(auto_now=True, verbose_name='Data inserimento')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punti_interesse.TipoInteresse', verbose_name='Tipologia')),
                ('estensione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punti_interesse.EstensioneInteresse', verbose_name='Estensione Interesse')),
                ('qualita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punti_interesse.QualitaInteresse', verbose_name='Qualità interesse')),
            ],
            options={
                'verbose_name': 'Punto di Interesse',
                'verbose_name_plural': 'Punti di Interesse',
            },
        ),
        migrations.AlterField(
            model_name='interessespecifico',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punti_interesse.TipoInteresse', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='puntointeresse',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punti_interesse.InteresseSpecifico', verbose_name='Oggetto Specifico'),
        ),
    ]
