# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-11 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('punti_interesse', '0003_auto_20190110_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidazionePunto',
            fields=[
                ('punto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='punti_interesse.PuntoInteresse')),
                ('validatore', models.CharField(max_length=128, verbose_name='Nome validatore')),
                ('descrizione', models.CharField(max_length=256, verbose_name='Descrizione')),
                ('data', models.DateField(auto_now=True, verbose_name='Data validazione')),
                ('data_aggiornamento', models.DateField(auto_now=True, verbose_name='Data aggiornamento')),
                ('regione', models.CharField(max_length=64, verbose_name='Regione')),
                ('comunita_montana', models.CharField(max_length=128, verbose_name='Comunità montana')),
                ('gruppo_montuoso', models.CharField(max_length=128, verbose_name='Gruppo montuoso')),
                ('quota', models.IntegerField(verbose_name='Quota')),
            ],
            options={
                'verbose_name': 'Validazione Punto',
                'verbose_name_plural': 'Validazione Punti',
            },
        ),
        migrations.AddField(
            model_name='puntointeresse',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interessespecifico',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='punti_interesse.TipoInteresse', verbose_name='Tipo'),
        ),
    ]
