# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-16 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('punti_interesse', '0005_auto_20190111_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoAccessoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='foto_accessorie/', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Foto Accessoria',
                'verbose_name_plural': 'Foto Accessorie',
            },
        ),
        migrations.AddField(
            model_name='puntointeresse',
            name='foto_copertina',
            field=models.ImageField(blank=True, null=True, upload_to='foto_copertina/', verbose_name='Foto copertina'),
        ),
        migrations.AddField(
            model_name='puntointeresse',
            name='rif_biblio',
            field=models.TextField(blank=True, max_length=256, verbose_name='Riferimenti bibliografici'),
        ),
        migrations.AddField(
            model_name='puntointeresse',
            name='rif_sito',
            field=models.TextField(blank=True, max_length=256, verbose_name='Riferimenti sitografici'),
        ),
        migrations.AlterField(
            model_name='puntointeresse',
            name='descr_estesa',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Descrizione oggetto estesa'),
        ),
        migrations.AlterField(
            model_name='puntointeresse',
            name='descr_sito',
            field=models.TextField(blank=True, max_length=256, verbose_name='Descrizione sito'),
        ),
        migrations.AlterField(
            model_name='puntointeresse',
            name='motivo',
            field=models.TextField(blank=True, max_length=256, verbose_name='Motivo per la fruizione'),
        ),
        migrations.AddField(
            model_name='fotoaccessoria',
            name='punto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punti_interesse.PuntoInteresse'),
        ),
    ]
