# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-30 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punti_interesse', '0006_auto_20190116_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntointeresse',
            name='validato',
            field=models.BooleanField(default=False, verbose_name='Validato'),
        ),
        migrations.AlterField(
            model_name='validazionepunto',
            name='descrizione',
            field=models.TextField(max_length=256, verbose_name='Descrizione'),
        ),
    ]
