# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 10:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import punti_interesse.validators


class Migration(migrations.Migration):

    dependencies = [
        ('punti_interesse', '0007_auto_20190130_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puntointeresse',
            old_name='tipo',
            new_name='sottocategoria',
        ),
        migrations.AlterField(
            model_name='puntointeresse',
            name='latitudine',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[punti_interesse.validators.validate_degree], verbose_name='Latitudine'),
        ),
        migrations.AlterField(
            model_name='puntointeresse',
            name='longitudine',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[punti_interesse.validators.validate_degree], verbose_name='Longitudine'),
        ),
        migrations.AlterField(
            model_name='validazionepunto',
            name='quota',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quota'),
        ),
    ]
