# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import punti_interesse.validators


class Migration(migrations.Migration):

    dependencies = [
        ('punti_interesse', '0008_auto_20190208_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoaccessoria',
            name='foto',
            field=models.ImageField(upload_to='foto_accessorie/', validators=[punti_interesse.validators.MaxSizeValidator(1)], verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='puntointeresse',
            name='foto_copertina',
            field=models.ImageField(blank=True, null=True, upload_to='foto_copertina/', validators=[punti_interesse.validators.MaxSizeValidator(1)], verbose_name='Foto copertina'),
        ),
    ]
