# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-02 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punti_interesse', '0009_auto_20190218_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntointeresse',
            name='rilevatore',
            field=models.CharField(default='Rilevatore', max_length=128, verbose_name='Nome rilevatore'),
            preserve_default=False,
        ),
    ]
