# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-02 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('punti_interesse', '0011_statoconservazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntointeresse',
            name='stato_conservazione',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='punti_interesse.StatoConservazione', verbose_name='Stato Conservazione'),
        ),
        migrations.AlterField(
            model_name='puntointeresse',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='punti_interesse.TipoInteresse', verbose_name='Tipologia'),
        ),
        migrations.AlterField(
            model_name='puntointeresse',
            name='estensione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='punti_interesse.EstensioneInteresse', verbose_name='Estensione Interesse'),
        ),
        migrations.AlterField(
            model_name='puntointeresse',
            name='qualita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='punti_interesse.QualitaInteresse', verbose_name='Qualità Interesse'),
        ),
        migrations.AlterField(
            model_name='puntointeresse',
            name='sottocategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='punti_interesse.InteresseSpecifico', verbose_name='Oggetto Specifico'),
        ),
    ]
