# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-05 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('punti_interesse', '0012_auto_20190302_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntointeresse',
            name='stato_conservazione',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='punti_interesse.StatoConservazione', verbose_name='Stato Conservazione'),
        ),
    ]
