# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-15 10:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('punti_interesse', '0014_auto_20190307_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntointeresse',
            name='rilevatore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utente rilevatore'),
        ),
        migrations.AlterField(
            model_name='validazionepunto',
            name='validatore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utente validatore'),
        ),
    ]
