# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-19 10:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import punti_interesse.validators


class Migration(migrations.Migration):

    dependencies = [
        ('punti_interesse', '0015_auto_20190315_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntointeresse',
            name='rilevatore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, validators=[punti_interesse.validators.validate_punto_rilevatore], verbose_name='Utente rilevatore'),
        ),
    ]
