# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-25 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punti_interesse', '0016_auto_20190319_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validazionepunto',
            name='regione',
            field=models.CharField(choices=[('VDA', "Valle d'Aosta"), ('PIE', 'Piemonte'), ('LOM', 'Lombardia'), ('TAA', 'Trentino Alto Adige'), ('VEN', 'Veneto'), ('FVG', 'Friuli Venezia Giulia'), ('LIG', 'Liguria'), ('ERM', 'Emilia Romagna'), ('TOS', 'Toscana'), ('UMB', 'Umbria'), ('MAR', 'Marche'), ('LAZ', 'Lazio'), ('ABR', 'Abruzzo'), ('MOL', 'Molise'), ('CAM', 'Campania'), ('BAS', 'Basilicata'), ('PUG', 'Puglia'), ('CAL', 'Calabria'), ('SIC', 'Sicilia'), ('SAR', 'Sardegna')], max_length=3, verbose_name='Regione'),
        ),
    ]
