# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-06 13:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('punti_interesse', '0018_auto_20190325_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, verbose_name='UUID')),
                ('sectioncode', models.IntegerField(verbose_name='Codice Sezione')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Informazioni Aggiuntive Utenti',
                'verbose_name_plural': 'Informazioni Aggiuntive Utenti',
            },
        ),
    ]
