# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-16 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import punti_interesse.validators


class Migration(migrations.Migration):

    dependencies = [
        ('punti_interesse', '0020_auto_20190415_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validazionepunto',
            name='data',
        ),
        migrations.AlterField(
            model_name='puntointeresse',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='punti_interesse.TipoInteresse', verbose_name='Tipologia*'),
        ),
        migrations.AlterField(
            model_name='puntointeresse',
            name='estensione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='punti_interesse.EstensioneInteresse', verbose_name='Estensione Interesse*'),
        ),
        migrations.AlterField(
            model_name='puntointeresse',
            name='latitudine',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[punti_interesse.validators.validate_degree], verbose_name='Latitudine*'),
        ),
        migrations.AlterField(
            model_name='puntointeresse',
            name='longitudine',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[punti_interesse.validators.validate_degree], verbose_name='Longitudine*'),
        ),
        migrations.AlterField(
            model_name='puntointeresse',
            name='qualita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='punti_interesse.QualitaInteresse', verbose_name='Qualità Interesse*'),
        ),
        migrations.AlterField(
            model_name='puntointeresse',
            name='sottocategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='punti_interesse.InteresseSpecifico', verbose_name='Oggetto Specifico*'),
        ),
        migrations.AlterField(
            model_name='puntointeresse',
            name='stato_conservazione',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='punti_interesse.StatoConservazione', verbose_name='Stato Conservazione*'),
        ),
        migrations.AlterField(
            model_name='puntointeresse',
            name='visitabile',
            field=models.BooleanField(verbose_name='Visitabile*'),
        ),
        migrations.AlterField(
            model_name='puntointeresse',
            name='visitabile2',
            field=models.BooleanField(verbose_name='Visitabile per persone con ridotta capacità motoria o sensoriale*'),
        ),
    ]
